version: '3.9'

services:

  python:
    image: python:3.8.2-alpine
    ports: 
      - "8002:8000"
    depends_on:
      - mariadb
    

  mariadb:
    image: mariadb
    restart: always
    ports:
        - "3307:3306"
    
    environment:
        MYSQL_DATABASE: pclaves_db
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_ROOT_PASSWORD: user



  