version: '3.9'

services:
  django-pep:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  # Monta el directorio backend en /app dentro del contenedor
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pep
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
    ports:
      - "1234:5432"

  